name: Build and Deploy Plot Site

on:
  push:
    branches: [ main ]
    paths: ['collections/**', '_config.yml', '_layouts/**', 'assets/**']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install snapshotplot
    
    - name: Build site
      run: |
        snapshotplot build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
